nome = 'Elias Lopes Mendes Hogashi'
print(nome[9])
print(nome[9:15])
print(nome[9:21:2])
print(nome[:9])
print(nome[9:])
print(nome[9::3])
print(len(nome))
print(nome.count('o'))
print(nome.count('o',0,13))
print(nome.find('lias'))
print(nome.find('endes'))
print(nome.count('android'))
print('Hogashi' in nome)
print(nome.replace('Hogashi','Android'))
print(nome)
nome = nome.replace('Hogashi','Android')
print(nome)
print(nome.upper())
print(nome.lower())
print(nome.capitalize())
print(nome.title())
print(len(nome))
nome = '     Elias Lopes Mendes Hogashi      '
print(nome)
print(len(nome))
print(nome.strip())
print(nome.rstrip())
print(nome.lstrip())
print(nome.split())
print(nome.split()[0])
print(nome.split()[2])
print('-'.join(nome))
nome = nome.split()
print('-'.join(nome))

